dev=vmdevopscicd1.dev.fyre.ibm.com:5565
test=vmdevopscicd2.dev.fyre.ibm.com:5565,vmdevopscicd1.dev.fyre.ibm.com:5515
qa=vmdevopscicd4.dev.fyre.ibm.com:5565,vmdevopscicd2.dev.fyre.ibm.com:5555
prod=vmdevopscicd3.dev.fyre.ibm.com:5565,vmdevopscicd4.dev.fyre.ibm.com:5565
